### PR TITLE
Add new "linux-pkg-build" action

### PR DESCRIPTION
**Pull request by prakashsurya**

### CODE REVIEW

**Comment by prakashsurya** [comment]
I tried to test this with the ZFS repository, by adding this to my personal fork of `delphix/zfs`:
```
± cat .github/workflows/main.yml 
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: prakashsurya/actions/linux-pkg-build@master
        with:
          package: zfs
```

The build appears to start up and execute properly, but it eventually failed.. Here's the build log ([link](https://github.com/prakashsurya/zfs/commit/c71a0806202544afbb4b3f74807466f8c9bf6914/checks/851381449/logs)).. I'm not yet sure if the build failed due to a bug in this PR, or something in the build/packaging of ZFS..

**Comment by prakashsurya** [comment]
Here's another example of how I expect this to be used: https://github.com/delphix/drgn/pull/16

**Comment by pzakha** [comment]
@prakashsurya So there's a few things that I could think of:

1. We are missing some packages installed by `./setup.sh`, although that's unlikely given you are installing most of them manually.
2. you are running `linux-pkg/buildpkg.sh` instead of `cd linux-pkg && ./buildpkg.sh` which may or may not work as I've never tested running buildpkg.sh outside of the `linux-pkg` directory. If that's the case we would want to fix that.
3. Something is different with the package dependencies fetched as setup.sh has apt pointing to the Delphix linux-package-mirror (although theoretically that should be following the default Ubuntu archive pretty closely on master).
4. Some packages were installed by default on bootstrap-18-04 that the zfs build relied on and we somehow missed.

Also I'm curious about what are you planning to use this linux-pkg action for.

**Comment by pzakha** [comment]
> Here's another example of how I expect this to be used: delphix/drgn#16

Ah okay, that makes sense.
Note that after the linux-pkg rework, some packages will require access to Delphix S3 buckets to build. Packages that have build dependencies on other linux-pkg packages, such as all kernel modules (zfs, connstat, delphix-kernel) are among those.

**Comment by prakashsurya** [comment]
> Note that after the linux-pkg rework, some packages will require access to Delphix S3 buckets to build.

Sure; either we'll not be able to build those via actions, or I'll look into if we could allow read access to those artifacts from these actions. I think it'd be reasonable to enable a read-only S3 token, but I haven't investigated that yet.

> 2. you are running linux-pkg/buildpkg.sh instead of cd linux-pkg && ./buildpkg.sh which may or may not work as I've never tested running buildpkg.sh outside of the linux-pkg directory. If that's the case we would want to fix that.

Ah, ok.. well, in that case, let me update this to change the working directory prior to calling the build script.

> 1. We are missing some packages installed by ./setup.sh, although that's unlikely given you are installing most of them manually.

I think it'd be ideal to call the setup script, but I didn't do that since it modifies the APT sources.. If we have a way to opt-out of the APT sources changes, I could probably call the setup script directly.

> 3. Something is different with the package dependencies fetched as setup.sh has apt pointing to the Delphix linux-package-mirror (although theoretically that should be following the default Ubuntu archive pretty closely on master).

Yea, I'm definitely a little concerned about using linux-pkg like this, while not having access to our APT mirrors... This might pose to be a blocking architecture issue, that we can't really overcome without running the action within our VPN.. but I figured I'd at least try this out and see how close to a working solution I could get.

**Comment by pzakha** [comment]
Cool, yeah I think it would be nice if we could stop having hard dependencies on the `bootstrap-18-04` VM. I think we should be able to build most packages from a docker container, although I do recall there was some quirks with some packages (bpftrace is one that comes to mind).

Regarding building the packages outside the VPN, here are the dependencies we currently use for the build of packages:
- Delphix S3 buckets
- Artifactory
- Linux package mirror
- Some secrets passed via Jenkins

**Pull request closed without merging**
